### PR TITLE
[UXE-36] Meteor Input Fields

### PR DESCRIPTION
**Pull request by gsamaniego41**
🎫 https://resolvn.atlassian.net/browse/UXE-36

Meteor theme component updates:

1. TextField
2. Select
3. Search
4. Autocomplete

### CODE REVIEW

**Comment by steve-jones** [comment]
image

Should the icon buttons be smaller in the "Size small" than in the "Size medium"

**Comment by steve-jones** [comment]
image

Small chip seems to have correct spacing to the right of the (X), medium has too little spacing to the right?

Also, inconsistent spacing between chip and "Favorites"

**Comment by steve-jones** [comment]
image

Select dropdown size broken

**Comment by gsamaniego41** [comment]
> Should the icon buttons be smaller in the "Size small" than in the "Size medium"

This is an MUI default, but yeah, it probably should. 

> Select dropdown size broken

> Autocomplete options way up high when not enough room to display below

I'm not able to reproduce these. 

> Small chip seems to have correct spacing to the right of the (X), medium has too little spacing to the right?
> 
> Also, inconsistent spacing between chip and "Favorites"

I believe both are FAD. I'll check the Classic theme specs in Figma.

**Review by steve-jones — APPROVED** [review]
Cool, just wanted to bring those up in case you thought any were issues that need to be addressed. But will approve and if you confirm those are FAD then you're good to merge.

**Pull request merged**
